---
alg: att-res-seq2seq
base_dir: log/att-res-seq2seq/forecast_data
log_level: INFO
gpu: 0
data:
  batch_size: 200
  dataset: data/forecast_data.npz
  test_size: 0.2
  valid_size: 0.2
model:
  seq_len: 24
  horizon: 1
  input_dim: 1
  l1_decay: 0
  num_nodes: 1
  output_dim: 1
  rnn_units: 100
  rnn_layers: 3
  verified_percentage: 1
train:
  dropout: 0.5
  epochs: 300
  optimizer: adam
  patience: 20
test:
  run_times: 1